/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import proyecto2.*;
import proyecto2.collections.consultorios;
import proyecto2.*;
import proyecto2.collections.consultorios;
import proyecto2.collections.Pacientes;
import proyecto2.collections.Pacientes;
import proyecto2.enums.colores;
import proyecto2.estructuras.HospitalManager;
import proyecto2.estructuras.ListaEnlazada;

public class Cantidaddeconsultorios extends javax.swing.JFrame {

    /**
     * Creates new form Cantidaddeconsultorios
     */
    public Cantidaddeconsultorios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        pacientesverdes = new javax.swing.JTextField();
        pacientesamarillos = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        pacientesrojos = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pacientesverdes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pacientesverdesActionPerformed(evt);
            }
        });
        getContentPane().add(pacientesverdes, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 120, 80, 30));
        getContentPane().add(pacientesamarillos, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, 80, 30));

        jButton1.setText("SIguiente");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 330, -1, -1));

        pacientesrojos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pacientesrojosActionPerformed(evt);
            }
        });
        getContentPane().add(pacientesrojos, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, 80, 30));

        jLabel3.setText("Consultorios pacientes amarillos");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, -1, -1));

        jLabel4.setText("Consultorios pacientes verdes");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 124, -1, 30));

        jLabel5.setText("Consultorios de emergencia");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondos-de-diapositivas-para-power-point-gratis-1.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pacientesverdesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pacientesverdesActionPerformed
                 // TODO add your handling code here:
    }//GEN-LAST:event_pacientesverdesActionPerformed

    private void pacientesrojosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pacientesrojosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pacientesrojosActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    String v=pacientesverdes.getText();
    String a=pacientesamarillos.getText();
    String r=pacientesrojos.getText();
     
    int verdes=Integer.parseInt(v);
    int amarillos=Integer.parseInt(a);
    int rojos=Integer.parseInt(r);
    int numeroconsultoriov=0;
    int numeroconsultorioa=0;
    int numeroconsultorior=0;
    
    while (verdes>0){
          numeroconsultoriov+=1;
          consultorios consultorio=new consultorios();
          consultorio.setNumeroconsultorio(numeroconsultoriov);
          consultorio.setDisponibilidad(true);
          consultorio.setIdentificador(colores.VERDE);
          HospitalManager.getInstance().agregarconsultoriov(consultorio);
          verdes-=1;
    }
    
     while (amarillos>0){
          numeroconsultorioa+=1;
          consultorios consultorio=new consultorios();
          consultorio.setNumeroconsultorio(numeroconsultorioa);
          consultorio.setDisponibilidad(true);
          HospitalManager.getInstance().agregarconsultorioa(consultorio);
          amarillos-=1;
    }
    while (rojos>0){
          numeroconsultorior+=1;
          consultorios consultorio=new consultorios();
          consultorio.setNumeroconsultorio(numeroconsultorior);
          consultorio.setDisponibilidad(true);
          HospitalManager.getInstance().agregarconsultorior(consultorio);
          rojos-=1;
          
    }
    // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cantidaddeconsultorios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cantidaddeconsultorios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cantidaddeconsultorios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cantidaddeconsultorios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cantidaddeconsultorios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField pacientesamarillos;
    private javax.swing.JTextField pacientesrojos;
    private javax.swing.JTextField pacientesverdes;
    // End of variables declaration//GEN-END:variables
}
