/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import proyecto2.collections.*;
import proyecto2.enums.*;
import proyecto2.estructuras.*;
import javax.swing.JOptionPane;
/**
 *
 * @author José Andres
 */
public class Registroingresos extends javax.swing.JFrame {

    /**
     * Creates new form Registroingresos
     */
    public Registroingresos() {
         initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        tipoenfermedad = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        pacientenombre = new javax.swing.JTextField();
        fechanacimientopaciente = new javax.swing.JTextField();
        detallep = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        tipopadecimiento = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField2 = new javax.swing.JTextField();

        jButton2.setText("jButton2");

        jLabel6.setText("Color");

        tipoenfermedad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoenfermedadActionPerformed(evt);
            }
        });

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Nombre del paciente");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Fecha de nacimiento");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, 20));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Detalles del padecimiento");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Tipo de padecimiento");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        pacientenombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pacientenombreActionPerformed(evt);
            }
        });
        getContentPane().add(pacientenombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 260, 30));

        fechanacimientopaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fechanacimientopacienteActionPerformed(evt);
            }
        });
        getContentPane().add(fechanacimientopaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 260, -1));

        detallep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detallepActionPerformed(evt);
            }
        });
        getContentPane().add(detallep, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 260, 50));

        jButton1.setText("Siguiente");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 250, -1, -1));

        tipopadecimiento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Infarto", "Hemorragia", "Parto", "Q", "Otro" }));
        tipopadecimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipopadecimientoActionPerformed(evt);
            }
        });
        getContentPane().add(tipopadecimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 160, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondos-de-diapositivas-para-power-point-gratis-1.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -80, 960, 410));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 260, -1));

        jTextField2.setText("jTextField2");
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pacientenombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pacientenombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pacientenombreActionPerformed

    private void tipoenfermedadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoenfermedadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipoenfermedadActionPerformed

    private void detallepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detallepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_detallepActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        
        
        String namep= pacientenombre.getText();
        String detailp= detallep.getText();
        String fecha= fechanacimientopaciente.getText();
        Pacientes paciente1= new Pacientes();
        paciente1.setDetallepadecimiento(detailp);
        paciente1.setFechanacimiento(fecha);
        paciente1.setNombre(namep);
        int i= tipopadecimiento.getSelectedIndex();
        if (i==0){
            paciente1.setTipopadecimento(tipopadecimientos.I);
        }
        if (i==1){
            paciente1.setTipopadecimento(tipopadecimientos.H);
        }
        if (i==2){
            paciente1.setTipopadecimento(tipopadecimientos.P);
        }
        if (i==3){
            paciente1.setTipopadecimento(tipopadecimientos.Q);
        }
        if (i==4){
            paciente1.setTipopadecimento(tipopadecimientos.O);
        }
        if (i==0||i==1){
            paciente1.setColor(colores.ROJO);
        }
        if (i==3 || i==2){
            paciente1.setColor(colores.AMARILLO);
        }
        if (i==4){
            paciente1.setColor(colores.VERDE);
        }
        if (paciente1.getColor()==colores.VERDE){
            HospitalManager.getInstance().agregarcolaprioridadv(paciente1);
        }
        if (paciente1.getColor()==colores.ROJO){
            HospitalManager.getInstance().agregarcolaprioridadr(paciente1);
        }
        if (paciente1.getColor()==colores.AMARILLO){
            HospitalManager.getInstance().agregarcolaprioridada(paciente1);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void fechanacimientopacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fechanacimientopacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fechanacimientopacienteActionPerformed

    private void tipopadecimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipopadecimientoActionPerformed
       
    }//GEN-LAST:event_tipopadecimientoActionPerformed

    /**
     * @param args the command line arguments
     * 
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registroingresos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registroingresos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registroingresos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registroingresos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registroingresos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField detallep;
    private javax.swing.JTextField fechanacimientopaciente;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField pacientenombre;
    private javax.swing.JTextField tipoenfermedad;
    private javax.swing.JComboBox<String> tipopadecimiento;
    // End of variables declaration//GEN-END:variables
}
